//! ZTSSH server daemon.
//!
//! Loads a Sub-CA key and IntermediateCertificate, then listens for ZTSSH
//! client connections and runs the continuous identity verification loop.
//!
//! Usage:
//!   ztsshd --cert intermediate.cert --key server.key [--listen 0.0.0.0:2222]

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;
use tracing_subscriber::EnvFilter;

use ztssh_audit::{emit, AuditEvent, AuditEventType, AuditOutcome};
use ztssh_ca::SubCa;
use ztssh_crypto::{IntermediateCertificate, KeyPair};
use ztssh_policy::PolicyEngine;
use ztssh_transport::server::ZtsshServer;

/// Transport mode: raw TCP or SSH.
#[derive(Clone, Debug, Default, clap::ValueEnum)]
enum TransportMode {
    /// Direct TCP transport (ZTSSH framing only).
    #[default]
    Tcp,
    /// SSH transport (ZTSSH protocol runs over SSH subsystem channel).
    Ssh,
}

/// ZTSSH server daemon — continuous identity verification.
#[derive(Parser)]
#[command(name = "ztsshd", version, about)]
struct Cli {
    /// IntermediateCertificate file (issued by Root CA).
    #[arg(long)]
    cert: String,

    /// Sub-CA private key file (32 bytes, generated by ztssh-ca generate-server-key).
    #[arg(long)]
    key: String,

    /// Listen address (default: 127.0.0.1:2222).
    #[arg(long, default_value = "127.0.0.1:2222")]
    listen: String,

    /// Challenge interval in seconds (default: 60).
    #[arg(long, default_value_t = ztssh_protocol::DEFAULT_CHALLENGE_INTERVAL)]
    challenge_interval: u32,

    /// Challenge deadline in seconds (default: 30).
    #[arg(long, default_value_t = ztssh_protocol::DEFAULT_CHALLENGE_DEADLINE)]
    challenge_deadline: u32,

    /// Log format: "text" (human-readable) or "json" (structured).
    #[arg(long, default_value = "text")]
    log_format: String,

    /// Policy configuration file (TOML). Optional.
    #[arg(long)]
    policy: Option<PathBuf>,

    /// Transport mode: "tcp" (default) or "ssh".
    #[arg(long, value_enum, default_value_t = TransportMode::Tcp)]
    mode: TransportMode,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    // Initialize tracing
    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));

    match cli.log_format.as_str() {
        "json" => {
            tracing_subscriber::fmt()
                .with_env_filter(filter)
                .json()
                .init();
        }
        _ => {
            tracing_subscriber::fmt()
                .with_env_filter(filter)
                .with_target(false)
                .init();
        }
    }

    // Load Sub-CA key
    let key_bytes: [u8; 32] = fs::read(&cli.key)
        .with_context(|| format!("failed to read key file: {}", cli.key))?
        .try_into()
        .map_err(|v: Vec<u8>| anyhow::anyhow!("key file must be 32 bytes, got {}", v.len()))?;
    let sub_ca_key = KeyPair::from_bytes(&key_bytes);

    // Load IntermediateCertificate
    let cert_bytes = fs::read(&cli.cert)
        .with_context(|| format!("failed to read certificate file: {}", cli.cert))?;
    let intermediate = IntermediateCertificate::from_wire(&cert_bytes)
        .map_err(|e| anyhow::anyhow!("failed to parse intermediate certificate: {e}"))?;

    tracing::info!(
        server_id = %intermediate.server_id,
        serial = intermediate.serial,
        principals = ?intermediate.allowed_principals,
        ttl = format!("{:.0}s", intermediate.ttl_remaining()),
        challenge_interval = cli.challenge_interval,
        challenge_deadline = cli.challenge_deadline,
        listen = %cli.listen,
        "ZTSSH server daemon starting"
    );

    if intermediate.is_expired() {
        anyhow::bail!("Intermediate certificate has expired. Request a new one from the Root CA.");
    }

    // Load policy
    let policy = match &cli.policy {
        Some(path) => {
            let engine = PolicyEngine::from_file(path)
                .with_context(|| format!("failed to load policy file: {}", path.display()))?;
            tracing::info!(path = %path.display(), "Policy loaded");
            emit(
                &AuditEvent::new(AuditEventType::PolicyLoaded, AuditOutcome::Success)
                    .detail(format!("Loaded from {}", path.display())),
            );
            engine
        }
        None => {
            tracing::info!("No policy file specified, using permissive defaults");
            PolicyEngine::permissive()
        }
    };

    let _ = policy; // Policy enforcement is handled by the transport layer

    // Build Sub-CA
    let mut sub_ca = SubCa::from_keypair(sub_ca_key);
    sub_ca.root_public_key = Some(intermediate.issuer_public_key);
    sub_ca.intermediate_cert = Some(intermediate);

    emit(
        &AuditEvent::new(AuditEventType::ServerStarted, AuditOutcome::Success).detail(format!(
            "Listening on {} (mode: {:?})",
            cli.listen, cli.mode
        )),
    );

    match cli.mode {
        TransportMode::Tcp => {
            // Direct TCP transport
            let server = ZtsshServer::new(sub_ca)
                .with_intervals(cli.challenge_interval, cli.challenge_deadline)
                .with_policy(policy);

            server
                .listen(&cli.listen)
                .await
                .map_err(|e| anyhow::anyhow!(e))
        }
        TransportMode::Ssh => {
            // SSH transport — ZTSSH protocol over SSH subsystem channels
            let config = ztssh_ssh::SshServerConfig::new(
                sub_ca,
                policy,
                cli.challenge_interval,
                cli.challenge_deadline,
            )
            .map_err(|e| anyhow::anyhow!("failed to create SSH server config: {e}"))?;

            let server = ztssh_ssh::server::ZtsshSshServer::new(config);
            server
                .listen(&cli.listen)
                .await
                .map_err(|e| anyhow::anyhow!("{e}"))
        }
    }
}
